import type { ChatSettings, ToolApprovalRequest } from './chat';

export interface Session {
  id: string;
  title: string;
  isAutoGeneratedTitle?: boolean;  // true = auto-generated, false = manually edited
  claudeSessionId: string | null;
  createdAt: string;
  updatedAt: string;
  settings: ChatSettings | null;
  isArchived: boolean;
  // Runtime state (from memory, not persisted)
  isProcessing?: boolean;
  pendingToolApproval?: ToolApprovalRequest | null;
}

export interface SessionSummary {
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  messageCount: number;
  isArchived: boolean;
  tagId: string | null;
  tagName: string | null;
}

export interface SessionListResponse {
  sessions: SessionSummary[];
  total: number;
  nextCursor: string | null;
  hasMore: boolean;
}

export interface SessionDetailResponse {
  session: Session;
  messages: import('./chat').Message[];
}
