-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Session" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "isAutoGeneratedTitle" BOOLEAN NOT NULL DEFAULT true,
    "claudeSessionId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "settings" TEXT,
    "allowedTools" TEXT,
    "skillSettings" TEXT,
    "isArchived" BOOLEAN NOT NULL DEFAULT false,
    "tagId" TEXT,
    CONSTRAINT "Session_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "Tag" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Session" ("allowedTools", "claudeSessionId", "createdAt", "id", "isArchived", "settings", "skillSettings", "tagId", "title", "updatedAt") SELECT "allowedTools", "claudeSessionId", "createdAt", "id", "isArchived", "settings", "skillSettings", "tagId", "title", "updatedAt" FROM "Session";
DROP TABLE "Session";
ALTER TABLE "new_Session" RENAME TO "Session";
CREATE INDEX "Session_tagId_idx" ON "Session"("tagId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
